GET http://localhost:3001/subscribers

###
GET http://localhost:3001/subscribers/66d427a71e7cba5aecda8547

###
POST http://localhost:3001/subscribers
Content-Type: application/json

{
    "name": "shru",
    "subscribedToChannel": "shru"
}

###
DELETE http://localhost:3001/subscribers/66d6ccef3bc70f77aa18b937

###
PATCH http://localhost:3001/subscribers/66d88c7a2e90dc718b54dc7f
Content-Type: application/json

{
    "name": "Amazingg"
}

### get all registered users
GET http://localhost:3001/register

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "shruthi",
    "email": "shruthi.anugowda@gmail.com",
    "password": "shruthi"
}

###
POST http://localhost:3001/register/users
Content-Type: application/json

{
    "name": "shruthi",
    "password": "shruthi"
}

###
GET  http://localhost:3001/users

###
GET http://localhost:3001/users?page=2&limit=5